---
- name: Install dependencies
  apt:
    name: "{{ 'gpg' if ansible_distribution_major_version is version('9','>') else 'gnupg' }}"

- name: Add Docker GPG Key
  apt_key: url=https://download.docker.com/linux/debian/gpg state=present

- name: Ensure Docker APT repo is present
  apt_repository:
    repo: "{{ docker_apt_repo }}"

- name: Install / update docker
  apt:
    name: "{{ docker_version }}"
    update_cache: true
  notify: restart docker
