---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: docker-ce-${MOLECULE_IMAGE}
    server_type: cx11
    image: ${MOLECULE_IMAGE}
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint -x 503
  flake8
  shellcheck_wrapper
