---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: ${DRONE_REPO_NAME}-${MOLECULE_IMAGE}-${REF}
    server_type: cx11
    image: ${MOLECULE_IMAGE}
provisioner:
  name: ansible
verifier:
  name: testinfra
