---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: docker-ce-${MOLECULE_INSTANCE_IMAGE}
    server_type: cx11
    image: ${MOLECULE_INSTANCE_IMAGE}
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        docker_version: "docker-ce=5:19.03.13~3-0~{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}"
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint -x 503
  flake8
  shellcheck_wrapper
